version: "3"
services:

  jenkins:
    image: 'jenkins/jenkins:lts'
    networks:
      - frontend
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
      JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - '8181:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
  #    - /var/run/docker.sock:/var/run/docker.sock
      - tomcat/webapps:/tomcat

  tomcat:
    image: tomcat:latest
    networks:
      - backend
      - frontend
    ports:
      - '8888:8080'
      - '9000:8000'
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socke
    volumes:
            # - ./tomcat/conf:/usr/local/tomcat/conf
      - tomcat/webapps:/usr/local/tomcat/webapps
    deploy:
      replicas: 3
      update_config: 3
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure

  jenkins-slave:
    environment:
      - 'JENKINS_URL=http://jenkins:8888'
    image: jenkins-slave
    networks:
      - backend
      - frontend
    volumes:
            #  - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
      - jenkins-workers:/var/jenkins_home # Avoid mysql volume mount issue
    depends_on:
      - jenkins


networks:
  frontend:
  backend:

volumes:
  jenkins_home:
    driver: overlay2
  tomcat/webapps:
    driver: overlay2
  jenkins-workers:
    driver: overlay2
